services:
  - type: web
    name: ssback-go
    runtime: go
    buildCommand: go mod tidy && go build -o server ./cmd/server
    startCommand: ./server
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: PORT
        value: "8000"
